server:
  port: 8890
spring:
  profiles: prod
  freemarker:
    cache: false
  datasource:
    username: localuser
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.162.137:3306/disk?characterEncoding=utf-8&serverTimezone=GMT%2B8
mybatis:
  type-aliases-package: com.aiyi.disk.entity
  mapper-locations: classpath:mappers/*.xml

# 支付宝相关
alipay:
  service: https://openapi.alipay.com/gateway.do
  aes: 6x0eFZVq8kqWBuYqIrFhVA==
  app-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmpPsWVRMttqFAGA+Pg95pZTUyj8rYBKoK4ZvUMLocdkjWjkLaWBujqIylhqGab8cmYbOw3Pk9PRgt9w9gtKIDqzHG5G2vr21+RZYbsH30vfVb4egC/VDiUDvlR7RxSofCmTDECej3PZI+7VypnpxYW5HUk1kcorS+4b89HGh1oR834HsiyRkWzg80VPZL3ERsCV2VyIbtSlY+2pKCj0r2JrSBjjD6CT7y5bhaLP/xzyCsn1HAOe8GNoG1VIG++MyByn8k5rL9cC9QktOH5KCAWFcTCTWBgeO6i0BOFThWhVm7fbbBDooOF07yPXJw9TQgYckCDvFXRKF1r+Fl/8J6wIDAQAB
  alipay-public-pay: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxt/bPSpdxv0idFDLw49EwMT1b0Ua9MuxzOdfH0E1O2a9sDfLfBye6m0MZtvgt9YYPL4k7UIjia3AIg9SX4IGWFDIA2MsVcxucab/MRa7YORcnE1+TIxj9djCfI8sLgjGN2r5NKI4oilAJ1WIrZ+2WTzWALRQMLqsLwk0qQsqnBrVAFoukLGX1Lj0FAalA4GL7K8SM8ag7qkiHtpwqTvbhZ5kH8utLYrt5Sp952+THSJKfZfzHiT1sruTqa/pXMYPGqDPY67K9zLUAqJ9G0Hzcnhdm98f/mo2izpX2I+2XpafuPjUfgBj6ny+L+ChqjLrF3PBXNXVRH0ddGEXLt4tWQIDAQAB
  appid: 2019070265735443
  app-private-key-path: /data/resource/app-private.key